//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTesting.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDominion")]
    public interface IDominion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDominion/Login", ReplyAction="http://tempuri.org/IDominion/LoginResponse")]
        void Login();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDominionChannel : ConsoleTesting.ServiceReference1.IDominion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DominionClient : System.ServiceModel.ClientBase<ConsoleTesting.ServiceReference1.IDominion>, ConsoleTesting.ServiceReference1.IDominion {
        
        public DominionClient() {
        }
        
        public DominionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DominionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DominionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DominionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Login() {
            base.Channel.Login();
        }
    }
}
